### ISSUE TITLE
Typos & clarifications

### ISSUE THREAD

**Issue by iteles** [nelsonic/learn-tdd#18]
Here are a few _**suggested**_ corrections of typos and/or clarifications!

I fixed the typos as I went along so I have these in a file (stupidly I forgot to fork and just cloned - so used to working on organisation documents!! :flushed: Happy to PR these in later today from a fork). I made the stuff below that I _didn't_ change in that file **bold** so you can see what they are straight away.

+ ["solving the solution"](https://github.com/nelsonic/learn-tdd/commit/6e4449f4b0da7fd93c39bc5f650d44722652c245#diff-04c6e90faac2675aa89e2176d2eec7d8R48) :arrow_right: comes across as confusing, 'solving the problem', 'finding a solution' or 'solving _for_ a solution' would all work better here
+ ["wihout a test"](https://github.com/nelsonic/learn-tdd/commit/6e4449f4b0da7fd93c39bc5f650d44722652c245#diff-04c6e90faac2675aa89e2176d2eec7d8R48) :arrow_right:  "without"
+ ["abut"](https://github.com/nelsonic/learn-tdd/commit/6e4449f4b0da7fd93c39bc5f650d44722652c245#diff-04c6e90faac2675aa89e2176d2eec7d8R50) :arrow_right: "about"
+ ["*faling*"](https://github.com/nelsonic/learn-tdd/commit/6e4449f4b0da7fd93c39bc5f650d44722652c245#diff-04c6e90faac2675aa89e2176d2eec7d8R59) :arrow_right: "failing"
+ ["write the code require"](https://github.com/nelsonic/learn-tdd/commit/6e4449f4b0da7fd93c39bc5f650d44722652c245#diff-04c6e90faac2675aa89e2176d2eec7d8R66) :arrow_right: "required"
+ ["By having a _clear_ question"](https://github.com/nelsonic/learn-tdd/commit/6e4449f4b0da7fd93c39bc5f650d44722652c245#diff-04c6e90faac2675aa89e2176d2eec7d8R72) :arrow_right: Capitalise 'By'
+ **I would possibly add 'no surprises, even when you're working with a big, inter-dependent code base' or something that gets people to understand that it's not 'wasted time'.**
+ **["e.g: `atom index.html`"](https://github.com/nelsonic/learn-tdd/commit/6e4449f4b0da7fd93c39bc5f650d44722652c245#diff-04c6e90faac2675aa89e2176d2eec7d8R100) :arrow_right: suggest adding (which creates and opens the file in the [Atom text editor](https://atom.io/) if you have it installed)**
+ ["So, back in our **index.html**"](https://github.com/nelsonic/learn-tdd/commit/6e4449f4b0da7fd93c39bc5f650d44722652c245#diff-04c6e90faac2675aa89e2176d2eec7d8R291) :arrow_right: Capitalise 'So'
+ ["We use Quint's"](https://github.com/nelsonic/learn-tdd/commit/6e4449f4b0da7fd93c39bc5f650d44722652c245#diff-04c6e90faac2675aa89e2176d2eec7d8R300) :arrow_right: QUnit
+ **Text on the [image of blanket test coverage](https://github.com/nelsonic/learn-tdd/commit/6e4449f4b0da7fd93c39bc5f650d44722652c245#diff-04c6e90faac2675aa89e2176d2eec7d8R720) is doubled up: "bad code on a single line **it will blanket will**..."**
+ [Sentence needs a full stop at the end](https://github.com/nelsonic/learn-tdd/commit/6e4449f4b0da7fd93c39bc5f650d44722652c245#diff-04c6e90faac2675aa89e2176d2eec7d8R720)
+ **I would add a one sentence explanation of what the code below these lines actually does [here](https://github.com/nelsonic/learn-tdd/commit/6e4449f4b0da7fd93c39bc5f650d44722652c245#diff-04c6e90faac2675aa89e2176d2eec7d8R720)**
+ **I would move [this line](https://github.com/nelsonic/learn-tdd/commit/6e4449f4b0da7fd93c39bc5f650d44722652c245#diff-04c6e90faac2675aa89e2176d2eec7d8R770) to the top of this bulleted block as people will read the bullets as instructions and maybe go away and try to install them separately without using `--save-dev`, get to this line and think they've done it all wrong**
+ ["roguge"](https://github.com/nelsonic/learn-tdd/commit/6e4449f4b0da7fd93c39bc5f650d44722652c245#diff-04c6e90faac2675aa89e2176d2eec7d8L786) :arrow_right: "rogue"
+ ["To quickly add CI support to your project."](https://github.com/nelsonic/learn-tdd/commit/6e4449f4b0da7fd93c39bc5f650d44722652c245#diff-04c6e90faac2675aa89e2176d2eec7d8R816) :arrow_right: punctuation; should be a `:` rather than a `.`
+ ["_**Note**_: the project will need to be hosted on GitHub"](https://github.com/nelsonic/learn-tdd/commit/6e4449f4b0da7fd93c39bc5f650d44722652c245#diff-04c6e90faac2675aa89e2176d2eec7d8R819) :arrow_right: Works much better when enclosed in brackets to separate it a little from the rest of the bullet
+ Capitalise the first letters of the [numbered list](https://github.com/nelsonic/learn-tdd/commit/6e4449f4b0da7fd93c39bc5f650d44722652c245#diff-04c6e90faac2675aa89e2176d2eec7d8R819) in bonus level 4 for consistency with the rest of the tutorial
+ ["lik"](https://github.com/nelsonic/learn-tdd/commit/6e4449f4b0da7fd93c39bc5f650d44722652c245#diff-04c6e90faac2675aa89e2176d2eec7d8R870) :arrow_right: "like"
+ Capitalise the first letters of the [unordered list](https://github.com/nelsonic/learn-tdd/commit/6e4449f4b0da7fd93c39bc5f650d44722652c245#diff-04c6e90faac2675aa89e2176d2eec7d8R881) in conclusion for consistency with the rest of the tutorial
+ ["descipline"](https://github.com/nelsonic/learn-tdd/commit/6e4449f4b0da7fd93c39bc5f650d44722652c245#diff-04c6e90faac2675aa89e2176d2eec7d8R881) :arrow_right: "discipline"
+ Remove full stop at the end of the bullet [in the middle of the bulleted list](https://github.com/nelsonic/learn-tdd/commit/6e4449f4b0da7fd93c39bc5f650d44722652c245#diff-04c6e90faac2675aa89e2176d2eec7d8R882) in the conclusion
+ ["if you have _**any questions**"](https://github.com/nelsonic/learn-tdd/commit/6e4449f4b0da7fd93c39bc5f650d44722652c245#diff-04c6e90faac2675aa89e2176d2eec7d8R888) :arrow_right: Capitalise "If"

**Comment by nelsonic** [comment]
Would you mind submitting these as a PR?

**Comment by iteles** [comment]
No problem :+1:

**Comment by iteles** [comment]
![learn-tdd-showing-rogue-code-on-one-line-goes-un-detected](https://cloud.githubusercontent.com/assets/4185328/8413913/f78be006-1e8b-11e5-940e-2f9bd22502bc.png)

**Comment by nelsonic** [comment]
Thanks again @iteles ! :heart:
